version: '3.9'

services:
  cliente_app:
    container_name: cliente_app
    image: cliente-app:1.0.0
    build: .
    ports:
      - "8090:8090"
    depends_on:
      - java_db
  java_db:
    container_name: java_db
    image: postgres
    #restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: banco